// auto-generated by scripts/build-exe.ts — do not edit
import a0 from "../client/dist/index.html" with { type: "file" }
import a1 from "../client/dist/og-image.png" with { type: "file" }
import a2 from "../client/dist/assets/opendaw-adapters-BikD_yTU.js" with { type: "file" }
import a3 from "../client/dist/assets/opendaw-core-DYCvPS_-.js" with { type: "file" }
import a4 from "../client/dist/assets/jszip.min-D7KnG0-e.js" with { type: "file" }
import a5 from "../client/dist/assets/opendaw-libs-YGTa5RcY.js" with { type: "file" }
import a6 from "../client/dist/assets/processors-CuavKsaG.js" with { type: "file" }
import a7 from "../client/dist/assets/SoundFont2-DfsoL6qi.js" with { type: "file" }
import a8 from "../client/dist/assets/index-DX7m6u94.js" with { type: "file" }
import a9 from "../client/dist/assets/workers-main-M1Zyc1cp.js" with { type: "file" }
import a10 from "../client/dist/assets/opendaw-boxes-7iIKc0eb.js" with { type: "file" }
import a11 from "../client/dist/assets/nam-B0sn4jDq.wasm" with { type: "file" }
import a12 from "../client/dist/assets/offline-engine-CvknxSQ0.js" with { type: "file" }
import a13 from "../client/dist/logo2.svg" with { type: "file" }
import a14 from "../client/dist/favicon.svg" with { type: "file" }

export const ASSETS: Record<string, string> = {
  "/index.html": a0,
  "/og-image.png": a1,
  "/assets/opendaw-adapters-BikD_yTU.js": a2,
  "/assets/opendaw-core-DYCvPS_-.js": a3,
  "/assets/jszip.min-D7KnG0-e.js": a4,
  "/assets/opendaw-libs-YGTa5RcY.js": a5,
  "/assets/processors-CuavKsaG.js": a6,
  "/assets/SoundFont2-DfsoL6qi.js": a7,
  "/assets/index-DX7m6u94.js": a8,
  "/assets/workers-main-M1Zyc1cp.js": a9,
  "/assets/opendaw-boxes-7iIKc0eb.js": a10,
  "/assets/nam-B0sn4jDq.wasm": a11,
  "/assets/offline-engine-CvknxSQ0.js": a12,
  "/logo2.svg": a13,
  "/favicon.svg": a14,
}
