// auto-generated by scripts/build-exe.ts — do not edit
import ytDlpAsset from "../vendor/yt-dlp" with { type: "file" }
import ffmpegAsset from "../vendor/ffmpeg" with { type: "file" }

export const VENDORED: { ytDlp: string; ffmpeg: string } = {
  ytDlp: ytDlpAsset,
  ffmpeg: ffmpegAsset,
}
