#!/usr/bin/env bun
// Build a standalone executable for the current platform.
// Pipeline: vite build → fetch yt-dlp + ffmpeg → generate static-import .gen.ts
// files → bun build --compile.

import { mkdir, writeFile, stat } from "node:fs/promises"
import { existsSync, readdirSync, statSync } from "node:fs"
import { resolve, relative, sep } from "node:path"
import { spawnSync } from "node:child_process"

import {
  fetchVendorBinaries,
  isPlatformSupported,
  vendorBinaryName,
  vendorPlatformKey,
  YTDLP_URLS,
} from "../server/vendor-fetch"

const ROOT = resolve(import.meta.dir, "..")

function log(msg: string): void {
  console.log(`→ ${msg}`)
}

function* walkFiles(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const p = resolve(dir, entry)
    if (statSync(p).isDirectory()) yield* walkFiles(p)
    else yield p
  }
}

// ───── Phase 1: build the React/Vite client ─────

log("phase 1: vite build")
// On Windows npm is a .cmd shim that Node can't spawn by bare name — use the
// platform-correct executable. (bun below is bun.exe and resolves fine.)
const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm"
const viteResult = spawnSync(
  npmCmd,
  ["-w", "@o-sample/client", "run", "build"],
  {
    cwd: ROOT,
    stdio: "inherit",
    // Empty string tells the SPA to use relative URLs — the exe serves the UI
    // and the API on the same origin, so no cross-origin fetch.
    env: { ...process.env, VITE_SAMPLE_SERVER_ORIGIN: "" },
  }
)
if (viteResult.status !== 0) process.exit(viteResult.status ?? 1)

const distDir = resolve(ROOT, "client/dist")
if (!existsSync(distDir)) {
  console.error("client/dist not found after vite build — aborting")
  process.exit(1)
}

// ───── Phase 2: vendor yt-dlp + ffmpeg for the current platform ─────

if (!isPlatformSupported()) {
  console.error(
    `unsupported platform: ${vendorPlatformKey()}\n` +
    `supported: ${Object.keys(YTDLP_URLS).join(", ")}`
  )
  process.exit(1)
}

log(`phase 2: vendor binaries for ${vendorPlatformKey()}`)
await fetchVendorBinaries(ROOT, msg => log(`  ${msg}`))

// ───── Phase 3: generate static-import .gen.ts files ─────

log("phase 3: generate embedded-asset imports")

const assetFiles = [...walkFiles(distDir)]
log(`  ${assetFiles.length} SPA files to embed`)

const assetImports: string[] = []
const assetMapEntries: string[] = []

assetFiles.forEach((filePath, i) => {
  const rel = relative(distDir, filePath).split(sep).join("/")
  const urlKey = "/" + rel
  const importPath = "../client/dist/" + rel
  const ident = `a${i}`
  assetImports.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" }`)
  assetMapEntries.push(`  ${JSON.stringify(urlKey)}: ${ident},`)
})

const assetsGen = [
  "// auto-generated by scripts/build-exe.ts — do not edit",
  ...assetImports,
  "",
  "export const ASSETS: Record<string, string> = {",
  ...assetMapEntries,
  "}",
  "",
].join("\n")

await writeFile(resolve(ROOT, "server/embedded-assets.gen.ts"), assetsGen)

const vendorGen = `// auto-generated by scripts/build-exe.ts — do not edit
import ytDlpAsset from "../vendor/${vendorBinaryName("yt-dlp")}" with { type: "file" }
import ffmpegAsset from "../vendor/${vendorBinaryName("ffmpeg")}" with { type: "file" }

export const VENDORED: { ytDlp: string; ffmpeg: string } = {
  ytDlp: ytDlpAsset,
  ffmpeg: ffmpegAsset,
}
`

await writeFile(resolve(ROOT, "server/vendored-binaries.gen.ts"), vendorGen)

// ───── Phase 4: bun build --compile ─────

log("phase 4: bun build --compile")

const distOut = resolve(ROOT, "dist")
await mkdir(distOut, { recursive: true })
const exeName = process.platform === "win32" ? "o-sample.exe" : "o-sample"
const outfile = resolve(distOut, exeName)

const compileResult = spawnSync(
  "bun",
  [
    "build",
    "--compile",
    "--target=bun",
    "--minify",
    "--sourcemap",
    resolve(ROOT, "server/serve-bundled.ts"),
    "--outfile",
    outfile,
  ],
  { cwd: ROOT, stdio: "inherit" }
)
if (compileResult.status !== 0) {
  console.error("bun build --compile failed")
  process.exit(compileResult.status ?? 1)
}

const finalStat = await stat(outfile)
const sizeMb = (finalStat.size / (1024 * 1024)).toFixed(1)
console.log(`\n✓ built ${relative(ROOT, outfile)}  (${sizeMb} MB)`)
console.log(`  run: ./${relative(process.cwd(), outfile)}\n`)
